/* eslint-disable import/prefer-default-export */
export const countryMapping: { [key: string]: string } = {
  AF: 'Afeganistão',
  AL: 'Albânia',
  DZ: 'Argélia',
  AD: 'Andorra',
  AO: 'Angola',
  AG: 'Antígua e Barbuda',
  AR: 'Argentina',
  AM: 'Armênia',
  AU: 'Austrália',
  AT: 'Áustria',
  AZ: 'Azerbaijão',
  BS: 'Bahamas',
  BH: 'Bahrein',
  BD: 'Bangladesh',
  BB: 'Barbados',
  BY: 'Bielorrússia',
  BE: 'Bélgica',
  BZ: 'Belize',
  BJ: 'Benin',
  BT: 'Butão',
  BO: 'Bolívia',
  BA: 'Bósnia e Herzegovina',
  BW: 'Botsuana',
  BR: 'Brasil',
  BN: 'Brunei',
  BG: 'Bulgária',
  BF: 'Burquina Faso',
  BI: 'Burundi',
  CV: 'Cabo Verde',
  KH: 'Camboja',
  CM: 'Camarões',
  CA: 'Canadá',
  CF: 'República Centro-Africana',
  TD: 'Chade',
  CL: 'Chile',
  CN: 'China',
  CO: 'Colômbia',
  KM: 'Comores',
  CG: 'República do Congo',
  CD: 'República Democrática do Congo',
  CR: 'Costa Rica',
  HR: 'Croácia',
  CU: 'Cuba',
  CY: 'Chipre',
  CZ: 'República Tcheca',
  DK: 'Dinamarca',
  DJ: 'Djibuti',
  DM: 'Dominica',
  DO: 'República Dominicana',
  EC: 'Equador',
  EG: 'Egito',
  SV: 'El Salvador',
  GQ: 'Guiné Equatorial',
  ER: 'Eritreia',
  EE: 'Estônia',
  SZ: 'Eswatini',
  ET: 'Etiópia',
  FJ: 'Fiji',
  FI: 'Finlândia',
  FR: 'França',
  GA: 'Gabão',
  GM: 'Gâmbia',
  GE: 'Geórgia',
  DE: 'Alemanha',
  GH: 'Gana',
  GR: 'Grécia',
  GD: 'Granada',
  GT: 'Guatemala',
  GN: 'Guiné',
  GW: 'Guiné-Bissau',
  GY: 'Guiana',
  HT: 'Haiti',
  HN: 'Honduras',
  HU: 'Hungria',
  IS: 'Islândia',
  IN: 'Índia',
  ID: 'Indonésia',
  IR: 'Irã',
  IQ: 'Iraque',
  IE: 'Irlanda',
  IL: 'Israel',
  IT: 'Itália',
  JM: 'Jamaica',
  JP: 'Japão',
  JO: 'Jordânia',
  KZ: 'Cazaquistão',
  KE: 'Quênia',
  KI: 'Quiribati',
  KP: 'Coreia do Norte',
  KR: 'Coreia do Sul',
  KW: 'Kuwait',
  KG: 'Quirguistão',
  LA: 'Laos',
  LV: 'Letônia',
  LB: 'Líbano',
  LS: 'Lesoto',
  LR: 'Libéria',
  LY: 'Líbia',
  LI: 'Liechtenstein',
  LT: 'Lituânia',
  LU: 'Luxemburgo',
  MG: 'Madagáscar',
  MW: 'Malawi',
  MY: 'Malásia',
  MV: 'Maldivas',
  ML: 'Mali',
  MT: 'Malta',
  MH: 'Ilhas Marshall',
  MR: 'Mauritânia',
  MU: 'Maurício',
  MX: 'México',
  FM: 'Estados Federados da Micronésia',
  MD: 'Moldova',
  MC: 'Mônaco',
  MN: 'Mongólia',
  ME: 'Montenegro',
  MA: 'Marrocos',
  MZ: 'Moçambique',
  MM: 'Mianmar',
  NA: 'Namíbia',
  NR: 'Nauru',
  NP: 'Nepal',
  NL: 'Países Baixos',
  NC: 'Nova Caledônia',
  NZ: 'Nova Zelândia',
  NI: 'Nicarágua',
  NE: 'Níger',
  NG: 'Nigéria',
  NU: 'Niue',
  NF: 'Ilha Norfolk',
  MP: 'Ilhas Marianas do Norte',
  NO: 'Noruega',
  OM: 'Omã',
  PK: 'Paquistão',
  PW: 'Palau',
  PS: 'Palestina',
  PA: 'Panamá',
  PG: 'Papua-Nova Guiné',
  PY: 'Paraguai',
  PE: 'Peru',
  PH: 'Filipinas',
  PN: 'Ilhas Pitcairn',
  PL: 'Polônia',
  PT: 'Portugal',
  PR: 'Porto Rico',
  QA: 'Catar',
  RE: 'Reunião',
  RO: 'Romênia',
  RU: 'Rússia',
  RW: 'Ruanda',
  BL: 'São Bartolomeu',
  SH: 'Santa Helena',
  KN: 'São Cristóvão e Nevis',
  LC: 'Santa Lúcia',
  MF: 'São Martinho',
  PM: 'São Pedro e Miquelon',
  VC: 'São Vicente e Granadinas',
  WS: 'Samoa',
  SM: 'San Marino',
  ST: 'São Tomé e Príncipe',
  SA: 'Arábia Saudita',
  SN: 'Senegal',
  RS: 'Sérvia',
  SC: 'Seicheles',
  SL: 'Serra Leoa',
  SG: 'Singapura',
  SX: 'Sint Maarten',
  SK: 'Eslováquia',
  SI: 'Eslovênia',
  SB: 'Ilhas Salomão',
  SO: 'Somália',
  ZA: 'África do Sul',
  SS: 'Sudão do Sul',
  ES: 'Espanha',
  LK: 'Sri Lanka',
  SD: 'Sudão',
  SR: 'Suriname',
  SJ: 'Svalbard e Jan Mayen',
  SE: 'Suécia',
  CH: 'Suíça',
  SY: 'Síria',
  TJ: 'Tajiquistão',
  TZ: 'Tanzânia',
  TH: 'Tailândia',
  TL: 'Timor-Leste',
  TG: 'Togo',
  TK: 'Tokelau',
  TO: 'Tonga',
  TT: 'Trinidad e Tobago',
  TN: 'Tunísia',
  TR: 'Turquia',
  TM: 'Turcomenistão',
  TC: 'Ilhas Turcas e Caicos',
  TV: 'Tuvalu',
  UG: 'Uganda',
  UA: 'Ucrânia',
  AE: 'Emirados Árabes Unidos',
  GB: 'Reino Unido',
  US: 'Estados Unidos',
  UY: 'Uruguai',
  UZ: 'Uzbequistão',
  VU: 'Vanuatu',
  VE: 'Venezuela',
  VN: 'Vietnã',
  WF: 'Wallis e Futuna',
  EH: 'Saara Ocidental',
  YE: 'Iémen',
  ZM: 'Zâmbia',
  ZW: 'Zimbábue',
};
